/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aQUI272OdiB
 */
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div key="1" className="flex flex-col w-full h-full p-4 bg-white dark:bg-gray-800 rounded-md shadow-lg">
      <div className="flex justify-between items-center mb-4">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Information Display</h1>
        <Button size="icon" variant="ghost">
          <IconSettings className="h-6 w-6 text-gray-500 dark:text-gray-200" />
          <span className="sr-only">Settings</span>
        </Button>
      </div>
      <div className="flex-1 overflow-auto">
        <img
          alt="Placeholder"
          className="w-1/2 mx-auto object-cover mb-4"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/200",
            objectFit: "cover",
          }}
          width="200"
        />
        <p className="text-sm text-gray-600 dark:text-gray-300 mb-4">
          Proin non odio sed nunc egestas fringilla at eu nulla. Vivamus in varius ex.
        </p>
        <p className="text-sm text-gray-600 dark:text-gray-300 mb-4">
          Ut nec justo vel diam elementum facilisis at ac felis. Sed ut mauris a ligula egestas tincidunt.
        </p>
      </div>
      <div className="flex justify-end mt-4">
        <Button className="mr-2" variant="outline">
          Cancel
        </Button>
        <Button>Confirm</Button>
      </div>
    </div>
  )
}


function IconSettings(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
